version: "3.7"
services:
  fc:
    build:
      args:
        user: deployer
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: base
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - base
  db:
    image: mysql:5.7 
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - base
    ports: 
      - '3307:3306'
    expose: 
      - '3306'

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - ./docker-compose/ssl:/etc/ssl
    networks:
      - base

volumes:
  db_data:
  
networks:
  base:
    driver: bridge

